### ISSUE TITLE
(not a bug) Medium per User XML

### ISSUE THREAD

**Issue by duncan** [myobie/fetcher#1]
You probably already know of this, but

https://gist.github.com/duncan/dfe840947d1b9e22da1e

I was digging through your fetcher code to see if there was a way to get a published date for an article, but it's not in the user page you're scraping. So, to get it that way would require fetching each article and pulling the pub date from it. That would suck. A bit more poking and I found there was a user XML feed. Not awesome, but not bad either. The thing it doesn't have is the nifty `3 min read` bit. 

Meh. Just FYI.

**Comment by myobie** [comment]
We could just fetch both.
